package DSassg2;


/**
* DSassg2/ServerInterface.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ServerInterface.idl
* Monday, July 31, 2017 4:57:43 PM EDT
*/

public interface ServerInterface extends ServerInterfaceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ServerInterface
